/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Analizador;

import com.sun.webkit.PageCache;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.Reader;
import java.io.StringReader;
import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;
import java_cup.runtime.Symbol;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SpringLayout;

/**
 *
 * @author mdelgado
 */
public class FrmAnalizador extends javax.swing.JFrame {

    /**
     * Creates new form FrmAnalizador
     */
    public FrmAnalizador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonAnalisis = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Resultado = new javax.swing.JTextArea();
        BotonSintactico = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAnalizarLex = new javax.swing.JTextArea();
        btnArchivo = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAnalizarSin = new javax.swing.JTextArea();
        Borrar1 = new javax.swing.JButton();
        Borrar2 = new javax.swing.JButton();
        jBtEjecutable = new javax.swing.JButton();
        jBtEjecutar = new javax.swing.JToggleButton();
        jBtIntermedio = new javax.swing.JButton();
        jBtAssembler = new javax.swing.JButton();
        jBtObjeto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotonAnalisis.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BotonAnalisis.setText("Análisis Léxico");
        BotonAnalisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAnalisisActionPerformed(evt);
            }
        });

        Resultado.setColumns(20);
        Resultado.setRows(5);
        jScrollPane1.setViewportView(Resultado);

        BotonSintactico.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BotonSintactico.setText("Análisis Sintático");
        BotonSintactico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSintacticoActionPerformed(evt);
            }
        });

        txtAnalizarLex.setColumns(20);
        txtAnalizarLex.setRows(5);
        jScrollPane2.setViewportView(txtAnalizarLex);

        btnArchivo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnArchivo.setText("Abrir Fuente");
        btnArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivoActionPerformed(evt);
            }
        });

        txtAnalizarSin.setColumns(20);
        txtAnalizarSin.setRows(5);
        jScrollPane3.setViewportView(txtAnalizarSin);

        Borrar1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Borrar1.setText("Borrar");
        Borrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Borrar1ActionPerformed(evt);
            }
        });

        Borrar2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Borrar2.setText("Borrar");
        Borrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Borrar2ActionPerformed(evt);
            }
        });

        jBtEjecutable.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBtEjecutable.setText("4 G Ejecutable");
        jBtEjecutable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtEjecutableActionPerformed(evt);
            }
        });

        jBtEjecutar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBtEjecutar.setText("5 Ejecutar");
        jBtEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtEjecutarActionPerformed(evt);
            }
        });

        jBtIntermedio.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBtIntermedio.setText("1 G Intermedio");
        jBtIntermedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtIntermedioActionPerformed(evt);
            }
        });

        jBtAssembler.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBtAssembler.setText("2 G Assembler");
        jBtAssembler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAssemblerActionPerformed(evt);
            }
        });

        jBtObjeto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBtObjeto.setText("3 G Objeto");
        jBtObjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtObjetoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotonSintactico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Borrar2))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotonAnalisis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(Borrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2))
                        .addGap(73, 73, 73))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtIntermedio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtAssembler, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtEjecutable, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jBtEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(312, 312, 312))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BotonAnalisis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Borrar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonSintactico, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Borrar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtObjeto, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jBtIntermedio, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jBtAssembler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtEjecutable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtEjecutar, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void analizarLexico() throws IOException {
        int cont = 1;

        String expr = (String) Resultado.getText();
        Lexico lexicos = new Lexico(new StringReader(expr));
        String resultado = "LINEA " + cont + "\t\tSIMBOLO\n";
        while (true) {
            Tokens token = lexicos.yylex();
            if (token == null) {
                txtAnalizarLex.setText(resultado);
                return;
            }
            switch (token) {
                case Linea:
                    cont++;
                    resultado += "LINEA " + cont + "\n";
                    break;
                case Comillas:
                    resultado += "  <Comillas>\t\t" + lexicos.lexemas + "\n";
                    break;
                case Cadena:
                    resultado += "  <Tipo de dato>\t" + lexicos.lexemas + "\n";
                    break;
                case T_dato:
                    resultado += "  <Tipo de dato>\t" + lexicos.lexemas + "\n";
                    break;
                case If:
                    resultado += "  <Reservada if>\t" + lexicos.lexemas + "\n";
                    break;
                case Int:
                    resultado += "  <Reservada int>\t" + lexicos.lexemas + "\n";
                    break;
                case Else:
                    resultado += "  <Reservada else>\t" + lexicos.lexemas + "\n";
                    break;
                case Abstract:
                    resultado += "  <Reservada abstract>\t" + lexicos.lexemas + "\n";
                    break;
                case As:
                    resultado += "  <Reservada as>\t" + lexicos.lexemas + "\n";
                    break;
                case Base:
                    resultado += "  <Reservada base>\t" + lexicos.lexemas + "\n";
                    break;
                case Catch:
                    resultado += "  <Reservada catch>\t" + lexicos.lexemas + "\n";
                    break;
                case Checked:
                    resultado += "  <Reservada checked>\t" + lexicos.lexemas + "\n";
                    break;
                case Class:
                    resultado += "  <Reservada class>\t" + lexicos.lexemas + "\n";
                    break;
                case Const:
                    resultado += "  <Reservada const>\t" + lexicos.lexemas + "\n";
                    break;
                case Decimal:
                    resultado += "  <Reservada decimal>\t" + lexicos.lexemas + "\n";
                    break;
                case Default:
                    resultado += "  <Reservada default>\t" + lexicos.lexemas + "\n";
                    break;
                case Delegate:
                    resultado += "  <Reservada delegate>\t" + lexicos.lexemas + "\n";
                    break;
                case Enum:
                    resultado += "  <Reservada enum>\t" + lexicos.lexemas + "\n";
                    break;
                case Event:
                    resultado += "  <Reservada event>\t" + lexicos.lexemas + "\n";
                    break;
                case Explicit:
                    resultado += "  <Reservada explicit>\t" + lexicos.lexemas + "\n";
                    break;
                case Extern:
                    resultado += "  <Reservada extern>\t" + lexicos.lexemas + "\n";
                    break;
                case Finally:
                    resultado += "  <Reservada finally>\t" + lexicos.lexemas + "\n";
                    break;
                case Bool:
                    resultado += "  <Reservada bool>\t" + lexicos.lexemas + "\n";
                    break;
                case False:
                    resultado += "  <Reservada false>\t" + lexicos.lexemas + "\n";
                    break;
                case True:
                    resultado += "  <Reservada true>\t" + lexicos.lexemas + "\n";
                    break;
                case Fixed:
                    resultado += "  <Reservada fixed>\t" + lexicos.lexemas + "\n";
                    break;
                case Foreach:
                    resultado += "  <Reservada foreach>\t" + lexicos.lexemas + "\n";
                    break;
                case Goto:
                    resultado += "  <Reservada goto>\t" + lexicos.lexemas + "\n";
                    break;
                case Implicit:
                    resultado += "  <Reservada implicit>\t" + lexicos.lexemas + "\n";
                    break;
                case In:
                    resultado += "  <Reservada in>\t" + lexicos.lexemas + "\n";
                    break;
                case Interface:
                    resultado += "  <Reservada interface>\t" + lexicos.lexemas + "\n";
                    break;
                case Internal:
                    resultado += "  <Reservada internal>\t" + lexicos.lexemas + "\n";
                    break;
                case Is:
                    resultado += "  <Reservada is>\t" + lexicos.lexemas + "\n";
                    break;
                case Lock:
                    resultado += "  <Reservada lock>\t" + lexicos.lexemas + "\n";
                    break;
                case Namespace:
                    resultado += "  <Reservada namespace>\t" + lexicos.lexemas + "\n";
                    break;
                case New:
                    resultado += "  <Reservada new>\t" + lexicos.lexemas + "\n";
                    break;
                case Null:
                    resultado += "  <Reservada null>\t" + lexicos.lexemas + "\n";
                    break;
                case Object:
                    resultado += "  <Reservada object>\t" + lexicos.lexemas + "\n";
                    break;
                case Operator:
                    resultado += "  <Reservada operator>\t" + lexicos.lexemas + "\n";
                    break;
                case Out:
                    resultado += " <Reservada out>\t" + lexicos.lexemas + "\n";
                    break;
                case Override:
                    resultado += " <Reservada override>\t" + lexicos.lexemas + "\n";
                    break;
                case Params:
                    resultado += " <Reservada params>\t" + lexicos.lexemas + "\n";
                    break;
                case Private:
                    resultado += " <Reservada private>\t" + lexicos.lexemas + "\n";
                    break;
                case Protected:
                    resultado += " <Reservada protected>\t" + lexicos.lexemas + "\n";
                    break;
                case Public:
                    resultado += " <Reservada public>\t" + lexicos.lexemas + "\n";
                    break;
                case Readonly:
                    resultado += " <Reservada readonly>\t" + lexicos.lexemas + "\n";
                    break;
                case Ref:
                    resultado += " <Reservada ref>\t" + lexicos.lexemas + "\n";
                    break;
                case Return:
                    resultado += " <Reservada return>\t" + lexicos.lexemas + "\n";
                    break;
                case Sbyte:
                    resultado += " <Reservada sbyte>\t" + lexicos.lexemas + "\n";
                    break;
                case Sealed:
                    resultado += " <Reservada sealed>\t" + lexicos.lexemas + "\n";
                    break;
                case Sizeof:
                    resultado += " <Reservada sizeof>\t" + lexicos.lexemas + "\n";
                    break;
                case Stackalloc:
                    resultado += " <Reservada stackalloc>\t" + lexicos.lexemas + "\n";
                    break;
                case Statict:
                    resultado += " <Reservada statict>\t" + lexicos.lexemas + "\n";
                    break;
                case Struct:
                    resultado += " <Reservada struct>\t" + lexicos.lexemas + "\n";
                    break;
                case This:
                    resultado += " <Reservada this>\t" + lexicos.lexemas + "\n";
                    break;
                case Throw:
                    resultado += " <Reservada throw>\t" + lexicos.lexemas + "\n";
                    break;
                case Try:
                    resultado += " <Reservada try>\t" + lexicos.lexemas + "\n";
                    break;
                case Typeof:
                    resultado += " <Reservada typeof>\t" + lexicos.lexemas + "\n";
                    break;
                case Uint:
                    resultado += " <Reservada uint>\t" + lexicos.lexemas + "\n";
                    break;
                case Ulong:
                    resultado += " <Reservada ulong>\t" + lexicos.lexemas + "\n";
                    break;
                case Unchecked:
                    resultado += " <Reservada unchecked>\t" + lexicos.lexemas + "\n";
                    break;
                case Unsafe:
                    resultado += " <Reservada unsafe>\t" + lexicos.lexemas + "\n";
                    break;
                case Ushort:
                    resultado += " <Reservada ushort>\t" + lexicos.lexemas + "\n";
                    break;
                case Using:
                    resultado += " <Reservada using>\t" + lexicos.lexemas + "\n";
                    break;
                case Virtual:
                    resultado += " <Reservada virtual>\t" + lexicos.lexemas + "\n";
                    break;
                case Volatile:
                    resultado += " <Reservada volatile>\t" + lexicos.lexemas + "\n";
                    break;
                case Void:
                    resultado += " <Reservada void>\t" + lexicos.lexemas + "\n";
                    break;
                case Switch:
                    resultado += "  <Reservada switch>\t" + lexicos.lexemas + "\n";
                    break;
                case Case:
                    resultado += "  <Reservada case>\t" + lexicos.lexemas + "\n";
                    break;
                case Break:
                    resultado += "  <Reservada break>\t" + lexicos.lexemas + "\n";
                    break;
                case Continue:
                    resultado += "  <Reservada continue>\t" + lexicos.lexemas + "\n";
                    break;
                case Do:
                    resultado += "  <Reservada do>\t" + lexicos.lexemas + "\n";
                    break;
                case While:
                    resultado += "  <Reservada while>\t" + lexicos.lexemas + "\n";
                    break;
                case For:
                    resultado += "  <Reservada for>\t" + lexicos.lexemas + "\n";
                    break;
                case Include:
                    resultado += "  <Reservada Include>\t" + lexicos.lexemas + "\n";
                    break;
                case Incluir:
                    resultado += "  <Reservada #Incluir>\t" + lexicos.lexemas + "\n";
                    break;
                case Dos_puntos:
                    resultado += "  <Operador dos_puntos>\t" + lexicos.lexemas + "\n";
                    break;
                case Igual:
                    resultado += "  <Operador igual>\t" + lexicos.lexemas + "\n";
                    break;
                case Suma:
                    resultado += "  <Operador suma>\t" + lexicos.lexemas + "\n";
                    break;
                case Resta:
                    resultado += "  <Operador resta>\t" + lexicos.lexemas + "\n";
                    break;
                case Multiplicacion:
                    resultado += "  <Operador multiplicacion>\t" + lexicos.lexemas + "\n";
                    break;
                case Division:
                    resultado += "  <Operador division>\t" + lexicos.lexemas + "\n";
                    break;
                case Y_Logico:
                    resultado += "  <Operador logico y_logico>\t" + lexicos.lexemas + "\n";
                    break;
                case O_Logico:
                    resultado += "  <Operador logico o_logico>\t" + lexicos.lexemas + "\n";
                    break;
                case Negacion:
                    resultado += "  <Operador logico negacion>\t" + lexicos.lexemas + "\n";
                    break;
                case Y_Logico_Bit:
                    resultado += "  <Operador logico y_logico_bit>\t" + lexicos.lexemas + "\n";
                    break;
                case O_Logico_Bit:
                    resultado += "  <Operador logico o_logico_bit>\t" + lexicos.lexemas + "\n";
                    break;
                case Menor_que:
                    resultado += "  <Operador relacional menor que>\t" + lexicos.lexemas + "\n";
                    break;
                case Mayor_que:
                    resultado += "  <Operador relacional mayor que>\t" + lexicos.lexemas + "\n";
                    break;
                case Igual_a:
                    resultado += "  <Operador relacional igual a>\t" + lexicos.lexemas + "\n";
                    break;
                case Diferente_de:
                    resultado += "  <Operador relacional diferente de>\t" + lexicos.lexemas + "\n";
                    break;
                case Mayor_o_igual_que:
                    resultado += "  <Operador relacional mayor o igual que>\t" + lexicos.lexemas + "\n";
                    break;
                case Menor_o_igual_que:
                    resultado += "  <Operador relacional menor o igual que>\t" + lexicos.lexemas + "\n";
                    break;
                case Desplazar_a_derecha:
                    resultado += "  <Operador de bit desplazar a derecha>\t" + lexicos.lexemas + "\n";
                    break;
                case Desplazar_a_izquierda:
                    resultado += "  <Operador de bit desplazar a izquierda>\t" + lexicos.lexemas + "\n";
                    break;
                case Asignacion_suma:
                    resultado += "  <Operador atribucion asignacion suma>\t" + lexicos.lexemas + "\n";
                    break;
                case Asignacion_resta:
                    resultado += "  <Operador atribucion asignacion resta>\t" + lexicos.lexemas + "\n";
                    break;
                case Asignacion_multiplicacion:
                    resultado += "  <Operador atribucion asignacion multiplicacion>\t" + lexicos.lexemas + "\n";
                    break;
                case Asignacion_division:
                    resultado += "  <Operador atribucion asignacion division>\t" + lexicos.lexemas + "\n";
                    break;
                case Asignacion_modulo:
                    resultado += "  <Operador atribucion asignacion modulo>\t" + lexicos.lexemas + "\n";
                    break;
                case Incremento_unitario:
                    resultado += "  <Operador incremento unitario>\t" + lexicos.lexemas + "\n";
                    break;
                case Decremento_unitario:
                    resultado += "  <Operador decremento unitario>\t" + lexicos.lexemas + "\n";
                    break;
                case Boleano_true:
                    resultado += "  <Operador boleano true>\t" + lexicos.lexemas + "\n";
                    break;
                case Boleano_false:
                    resultado += "  <Operador boleano false>\t" + lexicos.lexemas + "\n";
                    break;
                case Parentesis_a:
                    resultado += "  <Parentesis de apertura>\t" + lexicos.lexemas + "\n";
                    break;
                case Parentesis_c:
                    resultado += "  <Parentesis de cierre>\t" + lexicos.lexemas + "\n";
                    break;
                case Llave_a:
                    resultado += "  <Llave de apertura>\t" + lexicos.lexemas + "\n";
                    break;
                case Llave_c:
                    resultado += "  <Llave de cierre>\t" + lexicos.lexemas + "\n";
                    break;
                case Corchete_a:
                    resultado += "  <Corchete de apertura>\t" + lexicos.lexemas + "\n";
                    break;
                case Corchete_c:
                    resultado += "  <Corchete de cierre>\t" + lexicos.lexemas + "\n";
                    break;
                case Main:
                    resultado += "  <Reservada main>\t" + lexicos.lexemas + "\n";
                    break;
                case P_coma:
                    resultado += "  <Punto y coma>\t" + lexicos.lexemas + "\n";
                    break;
                case Punto:
                    resultado += "  <Punto>\t\t" + lexicos.lexemas + "\n";
                    break;
                case Numeral:
                    resultado += "  <Numeral>\t\t" + lexicos.lexemas + "\n";
                    break;
                case Identificador:
                    resultado += "  <Identificador>\t\t" + lexicos.lexemas + "\n";
                    break;
                case Numero:
                    resultado += "  <Numero>\t\t" + lexicos.lexemas + "\n";
                    break;
                case ERROR:
                    resultado += "  <Simbolo no definido>\n";
                    break;
                default:
                    resultado += "  < " + lexicos.lexemas + " >\n";
                    break;
            }
        }

    }

    private void BotonAnalisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAnalisisActionPerformed
        try {
            analizarLexico();
        } catch (IOException ex) {
            Logger.getLogger(FrmAnalizador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotonAnalisisActionPerformed

    private void Borrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Borrar2ActionPerformed
        txtAnalizarSin.setText(null);
    }//GEN-LAST:event_Borrar2ActionPerformed

    private void btnArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivoActionPerformed
        int cont = 1;
        JFileChooser escoger = new JFileChooser();
        escoger.showOpenDialog(null);
        
        File arc = new File(escoger.getSelectedFile().getAbsolutePath());
        //File arc = new File(escoger.getSelectedFile().getAbsolutePath());

        try {
            String ST = new String(Files.readAllBytes(arc.toPath()));
            Resultado.setText(ST);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrmAnalizador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FrmAnalizador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnArchivoActionPerformed

    private void BotonSintacticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSintacticoActionPerformed
        String ST = Resultado.getText();
        Sintaxis s = new Sintaxis(new Analizador.LexicoCup(new StringReader(ST)));

        try {
            s.parse();
            txtAnalizarSin.setText("Analisis realizado correctamente");
            txtAnalizarSin.setForeground(new Color(25, 111, 61));
        } catch (Exception ex) {
            Symbol sym = s.getS();
            txtAnalizarSin.setText("Error de sintaxis. Linea: " + (sym.right + 1) + " Columna: " + (sym.left + 1) + ", Texto: \"" + sym.value + "\"");
            txtAnalizarSin.setForeground(Color.red);
        }
    }//GEN-LAST:event_BotonSintacticoActionPerformed

    private void Borrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Borrar1ActionPerformed
        txtAnalizarLex.setText(null);
    }//GEN-LAST:event_Borrar1ActionPerformed

    private void jBtEjecutableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtEjecutableActionPerformed
        try {
            File f = new File("./Prueba.o");
            if (f.exists()) {
                String[] comando = {"../Archivos_bat/ejecutable.bat"};
                Runtime.getRuntime().exec(comando);
            } else {
                JOptionPane.showMessageDialog(null, "Falta el archivo .o");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jBtEjecutableActionPerformed

    private void jBtEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtEjecutarActionPerformed
        try {
            File f = new File("./Prueba.exe");
            if (f.exists()) {
                System.out.println(f.getName());
                String[] comando = {"../Archivos_bat/ejecutar.bat"};
                Runtime.getRuntime().exec(comando);
            } else {
                JOptionPane.showMessageDialog(null, "Falta el archivo .exe");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jBtEjecutarActionPerformed

    private void jBtIntermedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtIntermedioActionPerformed
        try {
            File f = new File("./Prueba.cpp");
            if (f.exists()) {
                String[] comando = {"../Archivos_bat/intermedio.bat"};
                Runtime.getRuntime().exec(comando);
            } else {
                JOptionPane.showMessageDialog(null, "Falta el archivo .cpp");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jBtIntermedioActionPerformed

    private void jBtAssemblerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAssemblerActionPerformed
        try {
            File f = new File("./Prueba.i");
            if (f.exists()) {
                String[] comando = {"../Archivos_bat/assembler.bat"};
                Runtime.getRuntime().exec(comando);
            } else {
                JOptionPane.showMessageDialog(null, "Falta el archivo .i");
            }

        } catch (IOException ex) {
            Logger.getLogger(FrmAnalizador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtAssemblerActionPerformed

    private void jBtObjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtObjetoActionPerformed
        try {
            File f = new File("./Prueba.s");
            if (f.exists()) {
                String[] comando = {"../Archivos_bat/objeto.bat"};
                Runtime.getRuntime().exec(comando);
            } else {
                JOptionPane.showMessageDialog(null, "Falta el archivo .s");
            }

        } catch (IOException ex) {
            Logger.getLogger(FrmAnalizador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtObjetoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAnalizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAnalizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAnalizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAnalizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAnalizador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Borrar1;
    private javax.swing.JButton Borrar2;
    private javax.swing.JButton BotonAnalisis;
    private javax.swing.JButton BotonSintactico;
    private javax.swing.JTextArea Resultado;
    private javax.swing.JButton btnArchivo;
    private javax.swing.JButton jBtAssembler;
    private javax.swing.JButton jBtEjecutable;
    private javax.swing.JToggleButton jBtEjecutar;
    private javax.swing.JButton jBtIntermedio;
    private javax.swing.JButton jBtObjeto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtAnalizarLex;
    private javax.swing.JTextArea txtAnalizarSin;
    // End of variables declaration//GEN-END:variables
}
