/* The following code was generated by JFlex 1.4.3 on 22/07/20 07:58 AM */

package Analizador;
import static Analizador.Tokens.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 22/07/20 07:58 AM from the specification file
 * <tt>../LexicoClase/src/Analizador/Lexico.flex</tt>
 */
class Lexico {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\10\2\0\1\3\22\0\1\3\1\50\1\11\2\0"+
    "\1\53\1\46\1\0\1\54\1\55\1\45\1\43\1\3\1\44\1\63"+
    "\1\7\12\2\1\41\1\62\1\52\1\42\1\51\2\0\22\1\1\30"+
    "\7\1\1\60\1\0\1\61\1\0\1\1\1\0\1\17\1\12\1\15"+
    "\1\25\1\14\1\24\1\23\1\16\1\4\1\37\1\31\1\21\1\32"+
    "\1\5\1\22\1\35\1\1\1\20\1\27\1\6\1\26\1\33\1\36"+
    "\1\34\1\13\1\40\1\56\1\47\1\57\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\3\2\1\5\1\6"+
    "\1\7\21\2\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\1\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\7\2\1\4\1\35\15\2\1\36\14\2\1\37\22\2"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\1\50\1\51\1\52\1\53\1\54\1\55\1\0\1\56"+
    "\1\2\1\57\5\2\1\60\23\2\1\61\3\2\1\62"+
    "\7\2\1\63\32\2\1\0\3\2\1\64\1\2\1\65"+
    "\1\2\1\66\1\67\1\70\1\2\1\71\1\72\1\73"+
    "\5\2\1\74\6\2\1\75\3\2\1\76\10\2\1\77"+
    "\15\2\1\100\1\2\1\101\7\2\1\3\4\2\1\102"+
    "\1\103\1\2\1\104\3\2\1\105\1\106\1\2\1\107"+
    "\7\2\1\110\1\111\5\2\1\112\1\113\5\2\1\114"+
    "\12\2\1\115\4\2\1\116\1\2\1\117\4\2\1\120"+
    "\1\2\1\121\7\2\1\122\1\123\1\124\2\2\1\125"+
    "\1\126\1\127\1\130\2\2\1\131\1\132\2\2\1\133"+
    "\5\2\1\134\5\2\1\135\1\136\1\137\2\2\1\140"+
    "\1\2\1\141\1\2\1\142\1\2\1\143\1\2\1\144"+
    "\1\2\1\145\1\146\1\147\1\150\1\151\1\152\1\153"+
    "\2\2\1\154\1\2\1\155\1\156\1\157\1\2\1\160"+
    "\1\161";

  private static int [] zzUnpackAction() {
    int [] result = new int[379];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\320\0\u0104\0\u0138\0\u016c"+
    "\0\u01a0\0\64\0\64\0\u01d4\0\u0208\0\u023c\0\u0270\0\u02a4"+
    "\0\u02d8\0\u030c\0\u0340\0\u0374\0\u03a8\0\u03dc\0\u0410\0\u0444"+
    "\0\u0478\0\u04ac\0\u04e0\0\u0514\0\64\0\u0548\0\u057c\0\u05b0"+
    "\0\u05e4\0\u0618\0\u064c\0\u0680\0\u06b4\0\u06e8\0\u071c\0\u0750"+
    "\0\64\0\64\0\64\0\64\0\64\0\64\0\64\0\u0784"+
    "\0\150\0\150\0\u07b8\0\u07ec\0\u0820\0\u0854\0\u0888\0\u08bc"+
    "\0\u08f0\0\u0924\0\64\0\u0958\0\u098c\0\u09c0\0\u09f4\0\u0a28"+
    "\0\u0a5c\0\u0a90\0\u0ac4\0\u0af8\0\u0b2c\0\u0b60\0\u0b94\0\u0bc8"+
    "\0\150\0\u0bfc\0\u0c30\0\u0c64\0\u0c98\0\u0ccc\0\u0d00\0\u0d34"+
    "\0\u0d68\0\u0d9c\0\u0dd0\0\u0e04\0\u0e38\0\u0e6c\0\u0ea0\0\u0ed4"+
    "\0\u0f08\0\u0f3c\0\u0f70\0\u0fa4\0\u0fd8\0\u100c\0\u1040\0\u1074"+
    "\0\u10a8\0\u10dc\0\u1110\0\u1144\0\u1178\0\u11ac\0\u11e0\0\u1214"+
    "\0\64\0\64\0\64\0\64\0\64\0\64\0\64\0\64"+
    "\0\64\0\64\0\64\0\64\0\64\0\64\0\u1248\0\u127c"+
    "\0\u12b0\0\150\0\u12e4\0\u1318\0\u134c\0\u1380\0\u13b4\0\150"+
    "\0\u13e8\0\u141c\0\u1450\0\u1484\0\u14b8\0\u14ec\0\u1520\0\u1554"+
    "\0\u1588\0\u15bc\0\u15f0\0\u1624\0\u1658\0\u168c\0\u16c0\0\u16f4"+
    "\0\u1728\0\u175c\0\u1790\0\150\0\u17c4\0\u17f8\0\u182c\0\150"+
    "\0\u1860\0\u1894\0\u18c8\0\u18fc\0\u1930\0\u1964\0\u1998\0\u19cc"+
    "\0\u1a00\0\u1a34\0\u1a68\0\u1a9c\0\u1ad0\0\u1b04\0\u1b38\0\u1b6c"+
    "\0\u1ba0\0\u1bd4\0\u1c08\0\u1c3c\0\u1c70\0\u1ca4\0\u1cd8\0\u1d0c"+
    "\0\u1d40\0\u1d74\0\u1da8\0\u1ddc\0\u1e10\0\u1e44\0\u1e78\0\u1eac"+
    "\0\u1ee0\0\u1f14\0\u1f48\0\u1f7c\0\u1fb0\0\u1fe4\0\150\0\u2018"+
    "\0\150\0\u204c\0\150\0\150\0\150\0\u2080\0\u20b4\0\150"+
    "\0\150\0\u20e8\0\u211c\0\u2150\0\u2184\0\u21b8\0\150\0\u21ec"+
    "\0\u2220\0\u2254\0\u2288\0\u22bc\0\u22f0\0\150\0\u2324\0\u2358"+
    "\0\u238c\0\150\0\u23c0\0\u23f4\0\u2428\0\u245c\0\u2490\0\u24c4"+
    "\0\u24f8\0\u252c\0\150\0\u2560\0\u2594\0\u25c8\0\u25fc\0\u2630"+
    "\0\u2664\0\u2698\0\u26cc\0\u2700\0\u2734\0\u2768\0\u279c\0\u27d0"+
    "\0\150\0\u2804\0\150\0\u2838\0\u286c\0\u28a0\0\u28d4\0\u2908"+
    "\0\u293c\0\u2970\0\64\0\u29a4\0\u29d8\0\u2a0c\0\u2a40\0\150"+
    "\0\150\0\u2a74\0\150\0\u2aa8\0\u2adc\0\u2b10\0\150\0\150"+
    "\0\u2b44\0\150\0\u2b78\0\u2bac\0\u2be0\0\u2c14\0\u2c48\0\u2c7c"+
    "\0\u2cb0\0\150\0\150\0\u2ce4\0\u2d18\0\u2d4c\0\u2d80\0\u2db4"+
    "\0\150\0\150\0\u2de8\0\u2e1c\0\u2e50\0\u2e84\0\u2eb8\0\150"+
    "\0\u2eec\0\u2f20\0\u2f54\0\u2f88\0\u2fbc\0\u2ff0\0\u3024\0\u3058"+
    "\0\u308c\0\u30c0\0\150\0\u30f4\0\u3128\0\u315c\0\u3190\0\150"+
    "\0\u31c4\0\150\0\u31f8\0\u322c\0\u3260\0\u3294\0\150\0\u32c8"+
    "\0\150\0\u32fc\0\u3330\0\u3364\0\u3398\0\u33cc\0\u3400\0\u3434"+
    "\0\150\0\150\0\150\0\u3468\0\u349c\0\150\0\150\0\150"+
    "\0\150\0\u34d0\0\u3504\0\150\0\150\0\u3538\0\u356c\0\150"+
    "\0\u35a0\0\u35d4\0\u3608\0\u363c\0\u3670\0\150\0\u36a4\0\u36d8"+
    "\0\u370c\0\u3740\0\u3774\0\150\0\150\0\150\0\u37a8\0\u37dc"+
    "\0\150\0\u3810\0\150\0\u3844\0\150\0\u3878\0\150\0\u38ac"+
    "\0\150\0\u38e0\0\150\0\150\0\150\0\150\0\150\0\150"+
    "\0\150\0\u3914\0\u3948\0\150\0\u397c\0\150\0\150\0\150"+
    "\0\u39b0\0\150\0\150";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[379];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\3\1\15\1\16\1\3\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\3\1\31\1\32\1\3\1\33\1\34\2\3"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\1\51\1\52\1\53\1\54"+
    "\1\55\1\56\1\57\65\0\2\3\1\0\3\3\3\0"+
    "\27\3\25\0\1\4\64\0\1\5\61\0\2\3\1\0"+
    "\1\3\1\60\1\3\3\0\12\3\1\61\2\3\1\62"+
    "\2\3\1\63\6\3\24\0\2\3\1\0\3\3\3\0"+
    "\2\3\1\64\2\3\1\65\6\3\1\66\12\3\24\0"+
    "\2\3\1\0\3\3\3\0\1\3\1\67\2\3\1\70"+
    "\1\3\1\71\20\3\32\0\1\72\32\0\1\73\22\0"+
    "\2\3\1\0\3\3\3\0\1\3\1\74\3\3\1\75"+
    "\1\76\1\3\1\77\16\3\24\0\2\3\1\0\1\3"+
    "\1\100\1\3\3\0\7\3\1\101\11\3\1\102\1\103"+
    "\4\3\24\0\2\3\1\0\3\3\3\0\4\3\1\104"+
    "\1\105\1\3\1\106\1\107\16\3\24\0\2\3\1\0"+
    "\3\3\3\0\1\110\14\3\1\111\11\3\24\0\2\3"+
    "\1\0\3\3\3\0\2\3\1\112\24\3\24\0\2\3"+
    "\1\0\3\3\3\0\10\3\1\113\16\3\24\0\2\3"+
    "\1\0\3\3\3\0\1\114\13\3\1\115\4\3\1\116"+
    "\1\3\1\117\3\3\24\0\2\3\1\0\3\3\3\0"+
    "\10\3\1\120\16\3\24\0\2\3\1\0\1\121\2\3"+
    "\3\0\5\3\1\122\1\3\1\123\1\124\16\3\24\0"+
    "\2\3\1\0\3\3\3\0\2\3\1\125\5\3\1\126"+
    "\16\3\24\0\2\3\1\0\1\127\1\130\1\3\3\0"+
    "\7\3\1\131\5\3\1\132\11\3\24\0\2\3\1\0"+
    "\1\133\1\3\1\134\3\0\1\135\1\3\1\136\1\3"+
    "\1\137\17\3\1\140\2\3\24\0\2\3\1\0\2\3"+
    "\1\141\3\0\27\3\24\0\2\3\1\0\3\3\3\0"+
    "\5\3\1\142\21\3\24\0\2\3\1\0\1\143\2\3"+
    "\3\0\10\3\1\144\16\3\24\0\2\3\1\0\3\3"+
    "\3\0\5\3\1\145\1\146\5\3\1\147\12\3\24\0"+
    "\2\3\1\0\3\3\3\0\4\3\1\150\22\3\65\0"+
    "\1\151\63\0\1\152\1\153\62\0\1\154\1\0\1\155"+
    "\61\0\1\156\67\0\1\157\64\0\1\160\56\0\1\161"+
    "\63\0\1\162\6\0\1\163\54\0\1\164\7\0\1\165"+
    "\53\0\1\166\65\0\1\167\20\0\2\3\1\0\2\3"+
    "\1\170\3\0\27\3\24\0\2\3\1\0\3\3\3\0"+
    "\23\3\1\171\3\3\24\0\2\3\1\0\3\3\3\0"+
    "\24\3\1\172\2\3\24\0\2\3\1\0\3\3\3\0"+
    "\20\3\1\173\6\3\24\0\2\3\1\0\3\3\3\0"+
    "\7\3\1\174\17\3\24\0\2\3\1\0\3\3\3\0"+
    "\23\3\1\175\3\3\24\0\2\3\1\0\1\176\2\3"+
    "\3\0\6\3\1\177\20\3\24\0\2\3\1\0\3\3"+
    "\3\0\1\3\1\200\12\3\1\201\12\3\23\0\10\72"+
    "\1\0\53\72\1\0\2\3\1\0\2\3\1\202\3\0"+
    "\27\3\24\0\2\3\1\0\3\3\3\0\15\3\1\203"+
    "\11\3\24\0\2\3\1\0\3\3\3\0\2\3\1\204"+
    "\24\3\24\0\2\3\1\0\3\3\3\0\10\3\1\205"+
    "\16\3\24\0\2\3\1\0\3\3\3\0\14\3\1\206"+
    "\12\3\24\0\2\3\1\0\3\3\3\0\15\3\1\207"+
    "\11\3\24\0\2\3\1\0\3\3\3\0\2\3\1\210"+
    "\24\3\24\0\2\3\1\0\2\3\1\211\3\0\23\3"+
    "\1\212\3\3\24\0\2\3\1\0\3\3\3\0\2\3"+
    "\1\213\2\3\1\214\21\3\24\0\2\3\1\0\2\3"+
    "\1\215\3\0\15\3\1\216\11\3\24\0\2\3\1\0"+
    "\3\3\3\0\5\3\1\217\21\3\24\0\2\3\1\0"+
    "\1\3\1\220\1\3\3\0\27\3\24\0\2\3\1\0"+
    "\3\3\3\0\15\3\1\221\11\3\24\0\2\3\1\0"+
    "\2\3\1\222\3\0\5\3\1\223\4\3\1\224\14\3"+
    "\24\0\2\3\1\0\1\3\1\225\1\3\3\0\3\3"+
    "\1\226\23\3\24\0\2\3\1\0\3\3\3\0\25\3"+
    "\1\227\1\3\24\0\2\3\1\0\2\3\1\230\3\0"+
    "\27\3\24\0\2\3\1\0\3\3\3\0\2\3\1\231"+
    "\24\3\24\0\2\3\1\0\3\3\3\0\2\3\1\232"+
    "\24\3\24\0\2\3\1\0\2\3\1\233\3\0\27\3"+
    "\24\0\2\3\1\0\1\3\1\234\1\3\3\0\22\3"+
    "\1\235\4\3\24\0\2\3\1\0\3\3\3\0\7\3"+
    "\1\236\17\3\24\0\2\3\1\0\3\3\3\0\10\3"+
    "\1\237\16\3\24\0\2\3\1\0\3\3\3\0\6\3"+
    "\1\240\20\3\24\0\2\3\1\0\3\3\3\0\3\3"+
    "\1\241\3\3\1\242\17\3\24\0\2\3\1\0\3\3"+
    "\3\0\14\3\1\243\12\3\24\0\2\3\1\0\1\3"+
    "\1\244\1\3\3\0\27\3\24\0\2\3\1\0\3\3"+
    "\3\0\3\3\1\245\11\3\1\246\11\3\24\0\2\3"+
    "\1\0\3\3\3\0\10\3\1\247\16\3\24\0\2\3"+
    "\1\0\1\250\2\3\3\0\4\3\1\251\22\3\24\0"+
    "\2\3\1\0\3\3\3\0\26\3\1\252\24\0\2\3"+
    "\1\0\3\3\3\0\5\3\1\253\1\254\20\3\24\0"+
    "\2\3\1\0\3\3\3\0\1\3\1\255\25\3\24\0"+
    "\2\3\1\0\3\3\3\0\5\3\1\256\21\3\24\0"+
    "\2\3\1\0\3\3\3\0\10\3\1\257\16\3\24\0"+
    "\2\3\1\0\1\260\2\3\3\0\27\3\24\0\2\3"+
    "\1\0\3\3\3\0\6\3\1\261\20\3\24\0\2\3"+
    "\1\0\1\262\2\3\3\0\27\3\24\0\2\3\1\0"+
    "\3\3\3\0\6\3\1\263\20\3\24\0\2\3\1\0"+
    "\1\264\2\3\3\0\7\3\1\265\17\3\24\0\2\3"+
    "\1\0\3\3\3\0\6\3\1\266\20\3\24\0\2\3"+
    "\1\0\1\267\2\3\3\0\10\3\1\270\16\3\24\0"+
    "\2\3\1\0\3\3\3\0\1\271\26\3\24\0\2\3"+
    "\1\0\1\272\2\3\3\0\27\3\25\0\1\273\62\0"+
    "\2\3\1\0\3\3\3\0\2\3\1\274\24\3\24\0"+
    "\2\3\1\0\3\3\3\0\7\3\1\275\17\3\24\0"+
    "\2\3\1\0\3\3\3\0\2\3\1\276\24\3\24\0"+
    "\2\3\1\0\3\3\3\0\7\3\1\277\17\3\24\0"+
    "\2\3\1\0\3\3\3\0\2\3\1\300\24\3\24\0"+
    "\2\3\1\0\3\3\3\0\15\3\1\301\11\3\24\0"+
    "\2\3\1\0\3\3\3\0\10\3\1\302\16\3\24\0"+
    "\2\3\1\0\3\3\3\0\2\3\1\303\24\3\24\0"+
    "\2\3\1\0\3\3\3\0\2\3\1\304\24\3\24\0"+
    "\2\3\1\0\3\3\3\0\2\3\1\305\24\3\24\0"+
    "\2\3\1\0\3\3\3\0\5\3\1\306\21\3\24\0"+
    "\2\3\1\0\3\3\3\0\7\3\1\307\17\3\24\0"+
    "\2\3\1\0\3\3\3\0\20\3\1\310\6\3\24\0"+
    "\2\3\1\0\3\3\3\0\2\3\1\311\24\3\24\0"+
    "\2\3\1\0\1\3\1\312\1\3\3\0\27\3\24\0"+
    "\2\3\1\0\3\3\3\0\2\3\1\313\24\3\24\0"+
    "\2\3\1\0\3\3\3\0\7\3\1\314\17\3\24\0"+
    "\2\3\1\0\3\3\3\0\3\3\1\315\23\3\24\0"+
    "\2\3\1\0\3\3\3\0\6\3\1\304\20\3\24\0"+
    "\2\3\1\0\3\3\3\0\3\3\1\316\23\3\24\0"+
    "\2\3\1\0\3\3\3\0\2\3\1\317\24\3\24\0"+
    "\2\3\1\0\3\3\3\0\15\3\1\320\11\3\24\0"+
    "\2\3\1\0\2\3\1\321\3\0\15\3\1\322\11\3"+
    "\24\0\2\3\1\0\2\3\1\323\3\0\27\3\24\0"+
    "\2\3\1\0\3\3\3\0\14\3\1\324\12\3\24\0"+
    "\2\3\1\0\3\3\3\0\13\3\1\325\13\3\24\0"+
    "\2\3\1\0\3\3\3\0\11\3\1\304\15\3\24\0"+
    "\2\3\1\0\3\3\3\0\17\3\1\326\7\3\24\0"+
    "\2\3\1\0\3\3\3\0\2\3\1\327\24\3\24\0"+
    "\2\3\1\0\3\3\3\0\6\3\1\330\20\3\24\0"+
    "\2\3\1\0\3\3\3\0\6\3\1\331\20\3\24\0"+
    "\2\3\1\0\3\3\3\0\10\3\1\332\16\3\24\0"+
    "\2\3\1\0\3\3\3\0\5\3\1\333\21\3\24\0"+
    "\2\3\1\0\3\3\3\0\2\3\1\334\24\3\24\0"+
    "\2\3\1\0\3\3\3\0\15\3\1\335\11\3\24\0"+
    "\2\3\1\0\3\3\3\0\5\3\1\336\21\3\24\0"+
    "\2\3\1\0\3\3\3\0\2\3\1\337\24\3\24\0"+
    "\2\3\1\0\1\340\2\3\3\0\27\3\24\0\2\3"+
    "\1\0\3\3\3\0\2\3\1\341\24\3\24\0\2\3"+
    "\1\0\3\3\3\0\1\342\26\3\24\0\2\3\1\0"+
    "\2\3\1\343\3\0\27\3\24\0\2\3\1\0\3\3"+
    "\3\0\4\3\1\344\22\3\24\0\2\3\1\0\3\3"+
    "\3\0\5\3\1\345\21\3\24\0\2\3\1\0\1\3"+
    "\1\346\1\3\3\0\27\3\24\0\2\3\1\0\1\3"+
    "\1\347\1\3\3\0\27\3\24\0\2\3\1\0\3\3"+
    "\3\0\10\3\1\350\16\3\24\0\2\3\1\0\3\3"+
    "\3\0\2\3\1\351\24\3\24\0\2\3\1\0\2\3"+
    "\1\352\3\0\3\3\1\353\23\3\24\0\2\3\1\0"+
    "\3\3\3\0\14\3\1\354\12\3\24\0\2\3\1\0"+
    "\2\3\1\355\3\0\27\3\24\0\2\3\1\0\3\3"+
    "\3\0\7\3\1\356\17\3\24\0\2\3\1\0\3\3"+
    "\3\0\6\3\1\336\20\3\24\0\2\3\1\0\2\3"+
    "\1\357\3\0\27\3\24\0\2\3\1\0\1\360\2\3"+
    "\3\0\27\3\24\0\2\3\1\0\1\3\1\361\1\3"+
    "\3\0\27\3\24\0\2\3\1\0\2\3\1\362\3\0"+
    "\27\3\24\0\2\3\1\0\3\3\3\0\13\3\1\363"+
    "\13\3\24\0\2\3\1\0\3\3\3\0\5\3\1\364"+
    "\21\3\24\0\2\3\1\0\3\3\3\0\5\3\1\365"+
    "\21\3\24\0\2\3\1\0\1\3\1\366\1\3\3\0"+
    "\21\3\1\367\5\3\24\0\2\3\1\0\2\3\1\370"+
    "\3\0\27\3\24\0\2\3\1\0\3\3\3\0\7\3"+
    "\1\371\17\3\24\0\2\3\1\0\3\3\3\0\7\3"+
    "\1\372\17\3\25\0\1\273\52\0\1\373\7\0\2\3"+
    "\1\0\3\3\3\0\6\3\1\374\20\3\24\0\2\3"+
    "\1\0\1\375\2\3\3\0\27\3\24\0\2\3\1\0"+
    "\3\3\3\0\15\3\1\376\11\3\24\0\2\3\1\0"+
    "\3\3\3\0\10\3\1\377\16\3\24\0\2\3\1\0"+
    "\3\3\3\0\24\3\1\u0100\2\3\24\0\2\3\1\0"+
    "\3\3\3\0\17\3\1\u0101\7\3\24\0\2\3\1\0"+
    "\3\3\3\0\2\3\1\u0102\24\3\24\0\2\3\1\0"+
    "\2\3\1\u0103\3\0\27\3\24\0\2\3\1\0\3\3"+
    "\3\0\6\3\1\u0104\20\3\24\0\2\3\1\0\1\u0105"+
    "\2\3\3\0\27\3\24\0\2\3\1\0\3\3\3\0"+
    "\17\3\1\u0106\7\3\24\0\2\3\1\0\3\3\3\0"+
    "\4\3\1\u0107\22\3\24\0\2\3\1\0\3\3\3\0"+
    "\15\3\1\u0108\11\3\24\0\2\3\1\0\1\u0109\2\3"+
    "\3\0\27\3\24\0\2\3\1\0\2\3\1\u010a\3\0"+
    "\27\3\24\0\2\3\1\0\3\3\3\0\6\3\1\u010b"+
    "\20\3\24\0\2\3\1\0\3\3\3\0\6\3\1\u010c"+
    "\20\3\24\0\2\3\1\0\3\3\3\0\10\3\1\u010d"+
    "\16\3\24\0\2\3\1\0\3\3\3\0\3\3\1\u010e"+
    "\23\3\24\0\2\3\1\0\3\3\3\0\6\3\1\u010f"+
    "\20\3\24\0\2\3\1\0\3\3\3\0\5\3\1\u0110"+
    "\21\3\24\0\2\3\1\0\3\3\3\0\7\3\1\u0111"+
    "\17\3\24\0\2\3\1\0\3\3\3\0\13\3\1\u0112"+
    "\13\3\24\0\2\3\1\0\3\3\3\0\2\3\1\u0113"+
    "\24\3\24\0\2\3\1\0\2\3\1\304\3\0\27\3"+
    "\24\0\2\3\1\0\3\3\3\0\5\3\1\u0114\21\3"+
    "\24\0\2\3\1\0\3\3\3\0\20\3\1\u0115\6\3"+
    "\24\0\2\3\1\0\3\3\3\0\11\3\1\u0116\15\3"+
    "\24\0\2\3\1\0\3\3\3\0\7\3\1\202\17\3"+
    "\24\0\2\3\1\0\3\3\3\0\2\3\1\u0117\24\3"+
    "\24\0\2\3\1\0\3\3\3\0\12\3\1\u0118\14\3"+
    "\24\0\2\3\1\0\3\3\3\0\11\3\1\u0119\15\3"+
    "\24\0\2\3\1\0\3\3\3\0\11\3\1\u011a\15\3"+
    "\24\0\2\3\1\0\3\3\3\0\6\3\1\u011b\20\3"+
    "\24\0\2\3\1\0\3\3\3\0\10\3\1\u011c\16\3"+
    "\24\0\2\3\1\0\1\u011d\2\3\3\0\27\3\24\0"+
    "\2\3\1\0\3\3\3\0\17\3\1\u011e\7\3\24\0"+
    "\2\3\1\0\3\3\3\0\3\3\1\u011f\23\3\24\0"+
    "\2\3\1\0\3\3\3\0\2\3\1\u0120\24\3\24\0"+
    "\2\3\1\0\3\3\3\0\2\3\1\u0121\24\3\24\0"+
    "\2\3\1\0\3\3\3\0\3\3\1\u0122\23\3\24\0"+
    "\2\3\1\0\1\3\1\u0123\1\3\3\0\27\3\24\0"+
    "\2\3\1\0\3\3\3\0\14\3\1\u0124\12\3\24\0"+
    "\2\3\1\0\2\3\1\u0125\3\0\27\3\24\0\2\3"+
    "\1\0\3\3\3\0\20\3\1\u0126\6\3\24\0\2\3"+
    "\1\0\2\3\1\u0127\3\0\27\3\24\0\2\3\1\0"+
    "\3\3\3\0\5\3\1\u0128\21\3\24\0\2\3\1\0"+
    "\3\3\3\0\2\3\1\u0129\24\3\24\0\2\3\1\0"+
    "\1\u012a\2\3\3\0\27\3\24\0\2\3\1\0\3\3"+
    "\3\0\2\3\1\u012b\24\3\24\0\2\3\1\0\1\3"+
    "\1\u012c\1\3\3\0\12\3\1\u012d\14\3\24\0\2\3"+
    "\1\0\3\3\3\0\3\3\1\u012e\23\3\24\0\2\3"+
    "\1\0\3\3\3\0\23\3\1\u012f\3\3\24\0\2\3"+
    "\1\0\3\3\3\0\12\3\1\u0130\14\3\24\0\2\3"+
    "\1\0\3\3\3\0\5\3\1\u0131\21\3\24\0\2\3"+
    "\1\0\1\3\1\u0132\1\3\3\0\27\3\24\0\2\3"+
    "\1\0\3\3\3\0\3\3\1\u0133\23\3\24\0\2\3"+
    "\1\0\3\3\3\0\2\3\1\u0134\24\3\24\0\2\3"+
    "\1\0\1\3\1\u0135\1\3\3\0\27\3\24\0\2\3"+
    "\1\0\3\3\3\0\5\3\1\u0136\21\3\24\0\2\3"+
    "\1\0\1\3\1\u0137\1\3\3\0\27\3\24\0\2\3"+
    "\1\0\1\3\1\u0138\1\3\3\0\27\3\24\0\2\3"+
    "\1\0\2\3\1\u0139\3\0\27\3\24\0\2\3\1\0"+
    "\1\u013a\2\3\3\0\27\3\24\0\2\3\1\0\2\3"+
    "\1\u013b\3\0\27\3\24\0\2\3\1\0\3\3\3\0"+
    "\7\3\1\u013c\17\3\24\0\2\3\1\0\3\3\3\0"+
    "\3\3\1\u013d\23\3\24\0\2\3\1\0\3\3\3\0"+
    "\5\3\1\u013e\21\3\24\0\2\3\1\0\3\3\3\0"+
    "\5\3\1\u013f\21\3\24\0\2\3\1\0\3\3\3\0"+
    "\3\3\1\u0140\23\3\24\0\2\3\1\0\3\3\3\0"+
    "\2\3\1\u0141\24\3\24\0\2\3\1\0\2\3\1\u0142"+
    "\3\0\27\3\24\0\2\3\1\0\3\3\3\0\12\3"+
    "\1\u0143\14\3\24\0\2\3\1\0\3\3\3\0\3\3"+
    "\1\u0144\23\3\24\0\2\3\1\0\3\3\3\0\5\3"+
    "\1\u0145\21\3\24\0\2\3\1\0\2\3\1\u0146\3\0"+
    "\27\3\24\0\2\3\1\0\3\3\3\0\13\3\1\u0147"+
    "\13\3\24\0\2\3\1\0\3\3\3\0\4\3\1\u0148"+
    "\22\3\24\0\2\3\1\0\3\3\3\0\11\3\1\u0149"+
    "\15\3\24\0\2\3\1\0\3\3\3\0\5\3\1\u014a"+
    "\21\3\24\0\2\3\1\0\1\u014b\2\3\3\0\27\3"+
    "\24\0\2\3\1\0\3\3\3\0\15\3\1\u014c\11\3"+
    "\24\0\2\3\1\0\3\3\3\0\12\3\1\u014d\14\3"+
    "\24\0\2\3\1\0\2\3\1\u014e\3\0\27\3\24\0"+
    "\2\3\1\0\3\3\3\0\3\3\1\u014f\23\3\24\0"+
    "\2\3\1\0\3\3\3\0\3\3\1\u0150\23\3\24\0"+
    "\2\3\1\0\3\3\3\0\5\3\1\u0151\21\3\24\0"+
    "\2\3\1\0\3\3\3\0\5\3\1\u0152\21\3\24\0"+
    "\2\3\1\0\1\u0153\2\3\3\0\27\3\24\0\2\3"+
    "\1\0\3\3\3\0\5\3\1\u0154\21\3\24\0\2\3"+
    "\1\0\1\3\1\304\1\3\3\0\27\3\24\0\2\3"+
    "\1\0\1\u0155\2\3\3\0\27\3\24\0\2\3\1\0"+
    "\3\3\3\0\13\3\1\u0156\13\3\24\0\2\3\1\0"+
    "\3\3\3\0\14\3\1\u0157\12\3\24\0\2\3\1\0"+
    "\3\3\3\0\3\3\1\u0158\23\3\24\0\2\3\1\0"+
    "\3\3\3\0\7\3\1\u0159\17\3\24\0\2\3\1\0"+
    "\3\3\3\0\13\3\1\u015a\13\3\24\0\2\3\1\0"+
    "\3\3\3\0\10\3\1\u015b\16\3\24\0\2\3\1\0"+
    "\3\3\3\0\1\3\1\u015c\25\3\24\0\2\3\1\0"+
    "\3\3\3\0\4\3\1\u015d\22\3\24\0\2\3\1\0"+
    "\3\3\3\0\7\3\1\u015e\17\3\24\0\2\3\1\0"+
    "\2\3\1\u015f\3\0\27\3\24\0\2\3\1\0\3\3"+
    "\3\0\17\3\1\u0160\7\3\24\0\2\3\1\0\2\3"+
    "\1\u0161\3\0\27\3\24\0\2\3\1\0\3\3\3\0"+
    "\7\3\1\u0162\17\3\24\0\2\3\1\0\3\3\3\0"+
    "\7\3\1\u0163\17\3\24\0\2\3\1\0\3\3\3\0"+
    "\7\3\1\u0164\17\3\24\0\2\3\1\0\3\3\3\0"+
    "\2\3\1\u0165\24\3\24\0\2\3\1\0\2\3\1\u0166"+
    "\3\0\27\3\24\0\2\3\1\0\3\3\3\0\7\3"+
    "\1\u0167\17\3\24\0\2\3\1\0\3\3\3\0\3\3"+
    "\1\u0168\23\3\24\0\2\3\1\0\2\3\1\u0169\3\0"+
    "\27\3\24\0\2\3\1\0\3\3\3\0\3\3\1\u016a"+
    "\23\3\24\0\2\3\1\0\2\3\1\u016b\3\0\27\3"+
    "\24\0\2\3\1\0\3\3\3\0\2\3\1\u016c\24\3"+
    "\24\0\2\3\1\0\2\3\1\u016d\3\0\27\3\24\0"+
    "\2\3\1\0\3\3\3\0\1\3\1\u016e\25\3\24\0"+
    "\2\3\1\0\3\3\3\0\2\3\1\u016f\24\3\24\0"+
    "\2\3\1\0\3\3\3\0\6\3\1\u0170\20\3\24\0"+
    "\2\3\1\0\3\3\3\0\2\3\1\u0171\24\3\24\0"+
    "\2\3\1\0\3\3\3\0\2\3\1\u0172\24\3\24\0"+
    "\2\3\1\0\3\3\3\0\7\3\1\u0173\17\3\24\0"+
    "\2\3\1\0\3\3\3\0\2\3\1\u0174\24\3\24\0"+
    "\2\3\1\0\3\3\3\0\2\3\1\u0175\24\3\24\0"+
    "\2\3\1\0\3\3\3\0\2\3\1\u0176\24\3\24\0"+
    "\2\3\1\0\3\3\3\0\2\3\1\u0177\24\3\24\0"+
    "\2\3\1\0\3\3\3\0\13\3\1\u0178\13\3\24\0"+
    "\2\3\1\0\3\3\3\0\10\3\1\u0179\16\3\24\0"+
    "\2\3\1\0\3\3\3\0\13\3\1\u017a\13\3\24\0"+
    "\2\3\1\0\3\3\3\0\3\3\1\u017b\23\3\23\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[14820];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\7\1\2\11\21\1\1\11\13\1\7\11"+
    "\13\1\1\11\55\1\16\11\1\0\103\1\1\0\77\1"+
    "\1\11\200\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[379];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexemas;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexico(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 134) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 17: 
          { lexemas=yytext(); return Mayor_que;
          }
        case 114: break;
        case 8: 
          { lexemas=yytext(); return Dos_puntos;
          }
        case 115: break;
        case 85: 
          { lexemas=yytext(); return Struct;
          }
        case 116: break;
        case 18: 
          { lexemas=yytext(); return Parentesis_a;
          }
        case 117: break;
        case 21: 
          { lexemas=yytext(); return Llave_c;
          }
        case 118: break;
        case 45: 
          { lexemas=yytext(); return Asignacion_modulo;
          }
        case 119: break;
        case 91: 
          { lexemas=yytext(); return Public;
          }
        case 120: break;
        case 81: 
          { lexemas=yytext(); return Object;
          }
        case 121: break;
        case 80: 
          { lexemas=yytext(); return Return;
          }
        case 122: break;
        case 10: 
          { lexemas=yytext(); return Suma;
          }
        case 123: break;
        case 104: 
          { lexemas=yytext(); return Readonly;
          }
        case 124: break;
        case 32: 
          { lexemas=yytext(); return Igual_a;
          }
        case 125: break;
        case 69: 
          { lexemas=yytext(); return Catch;
          }
        case 126: break;
        case 36: 
          { lexemas=yytext(); return Decremento_unitario;
          }
        case 127: break;
        case 51: 
          { lexemas=yytext(); return For;
          }
        case 128: break;
        case 103: 
          { lexemas=yytext(); return Abstract;
          }
        case 129: break;
        case 87: 
          { lexemas=yytext(); return Switch;
          }
        case 130: break;
        case 41: 
          { lexemas=yytext(); return Mayor_o_igual_que;
          }
        case 131: break;
        case 101: 
          { lexemas=yytext(); return Explicit;
          }
        case 132: break;
        case 40: 
          { lexemas=yytext(); return Diferente_de;
          }
        case 133: break;
        case 106: 
          { lexemas=yytext(); return Operator;
          }
        case 134: break;
        case 11: 
          { lexemas=yytext(); return Resta;
          }
        case 135: break;
        case 7: 
          { lexemas=yytext(); return Comillas;
          }
        case 136: break;
        case 13: 
          { lexemas=yytext(); return Y_Logico_Bit;
          }
        case 137: break;
        case 97: 
          { lexemas=yytext(); return Virtual;
          }
        case 138: break;
        case 86: 
          { lexemas=yytext(); return Sealed;
          }
        case 139: break;
        case 28: 
          { lexemas=yytext(); return Is;
          }
        case 140: break;
        case 5: 
          { lexemas=yytext(); return Division;
          }
        case 141: break;
        case 73: 
          { lexemas=yytext(); return False;
          }
        case 142: break;
        case 9: 
          { lexemas=yytext(); return Igual;
          }
        case 143: break;
        case 70: 
          { lexemas=yytext(); return Class;
          }
        case 144: break;
        case 12: 
          { lexemas=yytext(); return Multiplicacion;
          }
        case 145: break;
        case 29: 
          { lexemas=yytext(); return Asignacion_division;
          }
        case 146: break;
        case 48: 
          { lexemas=yytext(); return Try;
          }
        case 147: break;
        case 52: 
          { lexemas=yytext(); return Null;
          }
        case 148: break;
        case 4: 
          { /*Ignore*/
          }
        case 149: break;
        case 63: 
          { lexemas=yytext(); return Uint;
          }
        case 150: break;
        case 57: 
          { lexemas=yytext(); return Bool;
          }
        case 151: break;
        case 38: 
          { lexemas=yytext(); return Y_Logico;
          }
        case 152: break;
        case 44: 
          { lexemas=yytext(); return Desplazar_a_izquierda;
          }
        case 153: break;
        case 84: 
          { lexemas=yytext(); return Sizeof;
          }
        case 154: break;
        case 35: 
          { lexemas=yytext(); return Asignacion_resta;
          }
        case 155: break;
        case 33: 
          { lexemas=yytext(); return Asignacion_suma;
          }
        case 156: break;
        case 27: 
          { lexemas=yytext(); return If;
          }
        case 157: break;
        case 109: 
          { lexemas=yytext(); return Interface;
          }
        case 158: break;
        case 42: 
          { lexemas=yytext(); return Desplazar_a_derecha;
          }
        case 159: break;
        case 23: 
          { lexemas = yytext(); return Corchete_c;
          }
        case 160: break;
        case 58: 
          { lexemas=yytext(); return Enum;
          }
        case 161: break;
        case 82: 
          { lexemas=yytext(); return Unsafe;
          }
        case 162: break;
        case 43: 
          { lexemas=yytext(); return Menor_o_igual_que;
          }
        case 163: break;
        case 20: 
          { lexemas=yytext(); return Llave_a;
          }
        case 164: break;
        case 76: 
          { lexemas=yytext(); return Sbyte;
          }
        case 165: break;
        case 108: 
          { lexemas=yytext(); return Volatile;
          }
        case 166: break;
        case 74: 
          { lexemas=yytext(); return Ulong;
          }
        case 167: break;
        case 1: 
          { return ERROR;
          }
        case 168: break;
        case 25: 
          { lexemas=yytext(); return Punto;
          }
        case 169: break;
        case 78: 
          { lexemas=yytext(); return Typeof;
          }
        case 170: break;
        case 30: 
          { lexemas=yytext(); return As;
          }
        case 171: break;
        case 66: 
          { lexemas=yytext(); return Throw;
          }
        case 172: break;
        case 113: 
          { lexemas=yytext(); return Stackalloc;
          }
        case 173: break;
        case 94: 
          { lexemas=yytext(); return Foreach;
          }
        case 174: break;
        case 15: 
          { lexemas=yytext(); return Negacion;
          }
        case 175: break;
        case 96: 
          { lexemas=yytext(); return Statict;
          }
        case 176: break;
        case 90: 
          { lexemas=yytext(); return Printf;
          }
        case 177: break;
        case 92: 
          { lexemas=yytext(); return Checked;
          }
        case 178: break;
        case 72: 
          { lexemas=yytext(); return Fixed;
          }
        case 179: break;
        case 59: 
          { lexemas=yytext(); return Else;
          }
        case 180: break;
        case 39: 
          { lexemas=yytext(); return O_Logico;
          }
        case 181: break;
        case 22: 
          { lexemas = yytext(); return Corchete_a;
          }
        case 182: break;
        case 68: 
          { lexemas=yytext(); return Event;
          }
        case 183: break;
        case 62: 
          { lexemas=yytext(); return Goto;
          }
        case 184: break;
        case 64: 
          { lexemas=yytext(); return Main;
          }
        case 185: break;
        case 34: 
          { lexemas=yytext(); return Incremento_unitario;
          }
        case 186: break;
        case 99: 
          { lexemas=yytext(); return Internal;
          }
        case 187: break;
        case 2: 
          { lexemas=yytext(); return Identificador;
          }
        case 188: break;
        case 24: 
          { lexemas=yytext(); return P_coma;
          }
        case 189: break;
        case 49: 
          { lexemas=yytext(); return Ref;
          }
        case 190: break;
        case 77: 
          { lexemas=yytext(); return While;
          }
        case 191: break;
        case 60: 
          { lexemas=yytext(); return Case;
          }
        case 192: break;
        case 19: 
          { lexemas=yytext(); return Parentesis_c;
          }
        case 193: break;
        case 16: 
          { lexemas=yytext(); return Menor_que;
          }
        case 194: break;
        case 53: 
          { lexemas=yytext(); return This;
          }
        case 195: break;
        case 83: 
          { lexemas=yytext(); return Ushort;
          }
        case 196: break;
        case 6: 
          { return Linea;
          }
        case 197: break;
        case 47: 
          { lexemas=yytext(); return New;
          }
        case 198: break;
        case 50: 
          { lexemas=yytext(); return Out;
          }
        case 199: break;
        case 71: 
          { lexemas=yytext(); return Const;
          }
        case 200: break;
        case 110: 
          { lexemas=yytext(); return Namespace;
          }
        case 201: break;
        case 89: 
          { lexemas=yytext(); return Params;
          }
        case 202: break;
        case 105: 
          { lexemas=yytext(); return Override;
          }
        case 203: break;
        case 54: 
          { lexemas=yytext(); return True;
          }
        case 204: break;
        case 79: 
          { lexemas=yytext(); return Extern;
          }
        case 205: break;
        case 46: 
          { lexemas=yytext(); return Int;
          }
        case 206: break;
        case 56: 
          { lexemas=yytext(); return Base;
          }
        case 207: break;
        case 67: 
          { lexemas=yytext(); return Break;
          }
        case 208: break;
        case 107: 
          { lexemas=yytext(); return Delegate;
          }
        case 209: break;
        case 88: 
          { lexemas=yytext(); return Cadena;
          }
        case 210: break;
        case 61: 
          { lexemas=yytext(); return Lock;
          }
        case 211: break;
        case 75: 
          { lexemas=yytext(); return Using;
          }
        case 212: break;
        case 3: 
          { lexemas=yytext(); return Numero;
          }
        case 213: break;
        case 100: 
          { lexemas=yytext(); return Implicit;
          }
        case 214: break;
        case 14: 
          { lexemas=yytext(); return O_Logico_Bit;
          }
        case 215: break;
        case 37: 
          { lexemas=yytext(); return Asignacion_multiplicacion;
          }
        case 216: break;
        case 95: 
          { lexemas=yytext(); return Decimal;
          }
        case 217: break;
        case 93: 
          { lexemas=yytext(); return Finally;
          }
        case 218: break;
        case 98: 
          { lexemas=yytext(); return Private;
          }
        case 219: break;
        case 65: 
          { lexemas=yytext(); return Void;
          }
        case 220: break;
        case 111: 
          { lexemas=yytext(); return Unchecked;
          }
        case 221: break;
        case 31: 
          { lexemas=yytext(); return Do;
          }
        case 222: break;
        case 26: 
          { lexemas=yytext(); return In;
          }
        case 223: break;
        case 55: 
          { lexemas=yytext(); return T_dato;
          }
        case 224: break;
        case 112: 
          { lexemas=yytext(); return Protected;
          }
        case 225: break;
        case 102: 
          { lexemas=yytext(); return Continue;
          }
        case 226: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
